// ISSUE: Unittests with failing asserts should halt the program
// SHOULD: break
// NO_OUTPUT: true
// COMPILE_OPTIONS: unittest

unittest {
    assert(1 == 0, "1 failed to equal 0");
}

func main() {}
